server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $request_uri $request_uri/ /index.html;
    }

    # Handle assets separately to prevent them from being served as index.html
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|glb|gltf)$ {
        root /usr/share/nginx/html;
        expires 30d;
        add_header Cache-Control "public, no-cache, no-store, must-revalidate";
    }
}
