spring.profiles.active=qa

# Data Source Configuration
spring.datasource.url=${DB_URL_TEST}
spring.datasource.username=${DB_USERNAME_TEST}
spring.datasource.password=${DB_PASSWORD_TEST}
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Application Settings
spring.application.name=philosophy-rag-qa

# Vector Store Configuration
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=768

# File Upload Configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Ollama AI Configuration
spring.ai.ollama.embedding.enabled=true
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.options.model=nomic-embed-text-v2-moe
# Change this to the model you have pulled (e.g., llama3, gemma, mistral)
spring.ai.ollama.chat.enabled=true
spring.ai.ollama.chat.options.model=gemma4:31b-cloud
spring.ai.ollama.chat.options.temperature=0.7

# Logging & Error Handling
logging.level.org.apache.pdfbox.pdmodel.font.FileSystemFontProvider=ERROR

# JWT Secret Configuration
jwt.secret=${JWT_SECRET_KEY}

#AWS S3 Configuration
aws.region=ap-southeast-1
aws.s3.bucket-name=philosophy-learning-materials
aws.access-key-id=${AWS_ACCESS_KEY_ID}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY}
aws.s3.presigned-url-expiration-minutes=15