spring.config.activate.on-profile=dev
spring.docker.compose.enabled=false
# Data Source Configuration
spring.datasource.url=${DB_URL_DEV}
spring.datasource.username=${DB_USERNAME_DEV}
spring.datasource.password=${DB_PASSWORD_DEV}
spring.datasource.driverClassName=${DB_DRIVER_DEV}
spring.jpa.database-platform=${DB_PLATFORM_DEV}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO}
spring.jpa.show-sql=${SHOW_SQL}

# Application Settings
spring.application.name=philosophy-rag-dev

# Vector Store Configuration
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=768

# File Upload Configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Provider Switching (Can be overridden by ENV variable AI_PROVIDER)
ai.provider=${AI_PROVIDER:ollama}
voice.provider=${VOICE_PROVIDER:edge}

# Google AI Studio Configuration
spring.ai.google.genai.api-key=${GOOGLE_AI_STUDIO_API_KEY}
spring.ai.google.genai.chat.options.model=${MODEL_CHAT:gemini-2.5-flash}
spring.ai.google.genai.embedding.api-key=${GOOGLE_AI_STUDIO_API_KEY}
spring.ai.google.genai.embedding.text.options.model=${MODEL_EMBEDDING:gemini-embedding-001}

# Ollama AI Configuration
spring.ai.ollama.init.embedding.include=true
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.options.model=nomic-embed-text
spring.ai.ollama.init.chat.include=true
spring.ai.ollama.chat.options.model=gemma4:31b-cloud
spring.ai.ollama.chat.options.temperature=0.7

# ElevenLabs Configuration
elevenlabs.api-key=${ELEVENLABS_API_KEY}
elevenlabs.voice-id=${ELEVENLABS_VOICE_ID:Rachel}

# Cohere Configuration
cohere.api.key=${COHERE_API_KEY}
cohere.rerank.model=rerank-multilingual-v3.0
cohere.top.k=30


# Logging & Error Handling
logging.level.org.apache.pdfbox.pdmodel.font.FileSystemFontProvider=ERROR

# Data Initialization
spring.sql.init.mode=never
spring.sql.init.data-locations=classpath:data/initial_philosophers.sql

# JWT Secret Configuration
jwt.secret=${JWT_SECRET_KEY}

#AWS S3 Configuration
aws.region=ap-southeast-1
aws.s3.bucket-name=philosophy-learning-materials
aws.access-key-id=${AWS_ACCESS_KEY_ID}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY}
aws.s3.presigned-url-expiration-minutes=15

#Cloudinary Configuration
cloudinary.url=${CLOUDINARY_URL}
