#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
# ==========================================
#spring.datasource.url=jdbc:postgresql://localhost:5432/philoverse
#spring.datasource.username=postgres
#spring.datasource.password=12345
#spring.datasource.driverClassName=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# ==========================================
spring.application.name=philosophy-rag
# ==========================================
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=768
#=========Co the lay API Key cua AI khac de vao day =================
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.options.model=nomic-embed-text
#spring.ai.ollama.chat.options.model=gemma4:31b-cloud
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.apache.pdfbox.pdmodel.font.FileSystemFontProvider=ERROR
