spring.config.activate.on-profile=dev

# Data Source Configuration
spring.datasource.url=${DB_URL_DEV}
spring.datasource.username=${DB_USERNAME_DEV}
spring.datasource.password=${DB_PASSWORD_DEV}
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Application Settings
spring.application.name=philosophy-rag-dev

# Vector Store Configuration
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=768

# File Upload Configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Ollama AI Configuration
spring.ai.ollama.embedding.enabled=true
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.options.model=nomic-embed-text
# Change this to the model you have pulled (e.g., llama3, gemma, mistral)
spring.ai.ollama.chat.enabled=true
spring.ai.ollama.chat.options.model=gemma4:31b-cloud
spring.ai.ollama.chat.options.temperature=0.7

# Logging & Error Handling
logging.level.org.apache.pdfbox.pdmodel.font.FileSystemFontProvider=ERROR

# JWT Secret Configuration
jwt.secret=${JWT_SECRET_KEY}

