spring.config.activate.on-profile=prod
# Tắt hoàn toàn tính năng tự động quét và chạy Docker Compose
spring.docker.compose.enabled=false
# Data Source Configuration
spring.datasource.url=${DB_URL_PROD}
spring.datasource.username=${DB_USERNAME_PROD}
spring.datasource.password=${DB_PASSWORD_PROD}
spring.datasource.driverClassName=${DB_DRIVER_PROD}
spring.jpa.database-platform=${DB_PLATFORM_PROD}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO}
spring.jpa.show-sql=${SHOW_SQL}

# Application Settings
spring.application.name=philosophy-rag-prod

# Vector Store Configuration
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=768

# File Upload Configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Google AI Studio Configuration
spring.ai.google.genai.api-key=${GOOGLE_AI_STUDIO_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.embedding.text.options.model=text-embedding-004

# ElevenLabs Configuration
elevenlabs.api-key=${ELEVENLABS_API_KEY}
elevenlabs.voice-id=${ELEVENLABS_VOICE_ID:Rachel}

# Logging & Error Handling
logging.level.org.apache.pdfbox.pdmodel.font.FileSystemFontProvider=ERROR

# JWT Secret Configuration
jwt.secret=${JWT_SECRET_KEY}

#AWS S3 Configuration
aws.region=ap-southeast-1
aws.s3.bucket-name=philosophy-learning-materials
aws.access-key-id=${AWS_ACCESS_KEY_ID}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY}
aws.s3.presigned-url-expiration-minutes=15

#Cloudinary Configuration
cloudinary.url=${CLOUDINARY_URL}
